/**
 * Ambient declarations for the Node surface almostnode provides.
 *
 * The language service used to be configured with TypeScript's DOM library,
 * which is wrong twice over for these playgrounds: it offers completions for
 * things that do not exist at runtime (`alert`, `document`, and even
 * `ActiveXObject`), and it says nothing about `process`, `Buffer` or
 * `require`, which do. The JS/TS playgrounds load `lib.es*` plus
 * `lib.webworker` (the worker globals almostnode really has) and these
 * declarations on top.
 *
 * The shimmed modules are declared in shorthand (`declare module "fs";`),
 * which types them as `any`: enough for the checker to accept every import
 * shape without inventing errors about modules it cannot see, and honest
 * about the fact that these are shims rather than the real thing.
 */

/** Modules almostnode shims, each also reachable with the `node:` prefix. */
const SHIMMED_MODULES = [
  "assert",
  "async_hooks",
  "buffer",
  "child_process",
  "cluster",
  "console",
  "constants",
  "crypto",
  "dgram",
  "dns",
  "events",
  "fs",
  "fs/promises",
  "http",
  "http2",
  "https",
  "inspector",
  "module",
  "net",
  "os",
  "path",
  "path/posix",
  "perf_hooks",
  "process",
  "punycode",
  "querystring",
  "readline",
  "repl",
  "stream",
  "stream/promises",
  "string_decoder",
  "timers",
  "timers/promises",
  "tls",
  "tty",
  "url",
  "util",
  "v8",
  "vm",
  "worker_threads",
  "zlib",
];

const GLOBALS = `
declare interface NodeWritableStream {
  write(chunk: string | Uint8Array, encoding?: string, callback?: () => void): boolean;
  end(chunk?: string, callback?: () => void): void;
  isTTY: boolean;
  columns?: number;
}

declare interface NodeProcess {
  argv: string[];
  argv0: string;
  env: Record<string, string | undefined>;
  platform: string;
  arch: string;
  version: string;
  versions: Record<string, string>;
  pid: number;
  exitCode?: number;
  stdout: NodeWritableStream;
  stderr: NodeWritableStream;
  cwd(): string;
  chdir(directory: string): void;
  exit(code?: number): never;
  uptime(): number;
  memoryUsage(): { rss: number; heapTotal: number; heapUsed: number; external: number };
  hrtime: { (time?: [number, number]): [number, number]; bigint(): bigint };
  nextTick(callback: (...args: any[]) => void, ...args: any[]): void;
  on(event: string, listener: (...args: any[]) => void): NodeProcess;
  once(event: string, listener: (...args: any[]) => void): NodeProcess;
  off(event: string, listener: (...args: any[]) => void): NodeProcess;
  emit(event: string, ...args: any[]): boolean;
}

declare interface NodeBufferConstructor {
  from(value: string | ArrayLike<number> | ArrayBufferLike, encodingOrOffset?: any, length?: number): any;
  alloc(size: number, fill?: string | number, encoding?: string): any;
  allocUnsafe(size: number): any;
  concat(list: readonly Uint8Array[], totalLength?: number): any;
  isBuffer(value: unknown): boolean;
  byteLength(value: string | Uint8Array, encoding?: string): number;
}

declare var process: NodeProcess;
declare var Buffer: NodeBufferConstructor;
declare var global: typeof globalThis;
declare var __dirname: string;
declare var __filename: string;
declare var module: { exports: any; id: string; filename: string };
declare var exports: any;
declare function require(id: string): any;
declare namespace require {
  const cache: Record<string, any>;
  function resolve(id: string): string;
}
declare function setImmediate(callback: (...args: any[]) => void, ...args: any[]): any;
declare function clearImmediate(handle: any): void;
`;

/** The declaration file mounted for the Node-flavoured playgrounds. */
export const NODE_AMBIENT_TYPES: string = [
  "// Generated by nodeAmbientTypes.ts for the JS/TS playgrounds.",
  GLOBALS.trim(),
  ...SHIMMED_MODULES.flatMap((name) => [
    `declare module "${name}";`,
    `declare module "node:${name}";`,
  ]),
  "",
].join("\n");

/** Path the declarations are mounted at inside the language service host. */
export const NODE_AMBIENT_TYPES_PATH = "/__pg/node-globals.d.ts";
