"use client";

/**
 * Carries one lesson's prepopulated code-block outputs from the page down to
 * the `<CodeBlock>`s inside its MDX.
 *
 * The manifest is generated by `scripts/build-block-outputs.mjs` and is
 * whole-site; the page picks out its own lesson's slice and provides only
 * that, so a reader downloads the outputs for the lesson they are reading
 * and nothing else. A context (rather than a prop threaded through MDX) is
 * the only way in: the blocks are authored as JSX inside the content, so
 * nothing on the route can reach them directly.
 *
 * Absent context, absent lesson, absent entry — every miss degrades to the
 * same thing, an empty output panel, which is exactly how these blocks
 * behaved before any of this existed.
 */

import { createContext, useContext, type ReactNode } from "react";
import type { BareOutputCell } from "../runtime/pythonDisplayOutputs";

export interface PrepopulatedOutput {
  cells: BareOutputCell[];
  /** False when two build-time runs of the block disagreed. Recorded for
   *  reporting; the UI labels every prepopulated panel a preview either
   *  way, because "is this deterministic?" is not a question a label
   *  should be asking the reader to care about. */
  stable: boolean;
}

export type LessonBlockOutputs = Record<string, PrepopulatedOutput>;

const BlockOutputsContext = createContext<LessonBlockOutputs | null>(null);

export function BlockOutputsProvider({
  outputs,
  children,
}: {
  outputs: LessonBlockOutputs | null;
  children: ReactNode;
}) {
  return (
    <BlockOutputsContext.Provider value={outputs}>
      {children}
    </BlockOutputsContext.Provider>
  );
}

/** The recorded output for `key`, or null when there isn't one. */
export function usePrepopulatedOutput(key: string): PrepopulatedOutput | null {
  const outputs = useContext(BlockOutputsContext);
  return outputs?.[key] ?? null;
}
