"use client";

/**
 * Carries one lesson's prepopulated code-block outputs (generated by
 * scripts/build-block-outputs.mjs) down to the `<CodeBlock>`s in its MDX. A
 * context is the only way in — the blocks are authored as JSX inside content.
 * The page provides only its own lesson's slice; every miss degrades to an
 * empty output panel.
 */

import { createContext, useContext, type ReactNode } from "react";
import type { BareOutputCell } from "../runtime/pythonDisplayOutputs";

export interface PrepopulatedOutput {
  cells: BareOutputCell[];
  /** False when two build-time runs disagreed. Recorded for reporting; the UI
   *  labels every prepopulated panel a preview either way. */
  stable: boolean;
}

export type LessonBlockOutputs = Record<string, PrepopulatedOutput>;

const BlockOutputsContext = createContext<LessonBlockOutputs | null>(null);

export function BlockOutputsProvider({
  outputs,
  children,
}: {
  outputs: LessonBlockOutputs | null;
  children: ReactNode;
}) {
  return (
    <BlockOutputsContext.Provider value={outputs}>
      {children}
    </BlockOutputsContext.Provider>
  );
}

/** The recorded output for `key`, or null when there isn't one. */
export function usePrepopulatedOutput(key: string): PrepopulatedOutput | null {
  const outputs = useContext(BlockOutputsContext);
  return outputs?.[key] ?? null;
}
