/**
 * Server-safe registry of the React-course demo components; deliberately NOT
 * `"use client"`. RSC turns every export of a client module into an opaque
 * client reference, so an object exported from lazyReactDemos.ts would spread
 * to nothing on the server — re-collecting the named imports here produces a
 * real, spreadable object.
 */

import {
  GreetingDemo,
  StarRatingDemo,
  AvatarDemo,
  UserCardDemo,
  BadgeDemo,
  ListDemo,
  FilterListDemo,
  CounterDemo,
  ToggleDemo,
  ColorPickerDemo,
  LikeButtonDemo,
  KeyPressDemo,
  TextMirrorDemo,
  SignupFormDemo,
  TemperatureDemo,
  ClockDemo,
  WindowWidthDemo,
  DataFetchDemo,
  PanelDemo,
  SlotsDemo,
  TabsDemo,
  ChildrenCountDemo,
  UseToggleDemo,
  StopwatchDemo,
  UseLocalStorageDemo,
  TodoDemo,
  AuthToggleDemo,
  CartBadgeDemo,
  ImmutableListDemo,
  SettingsObjectDemo,
  FocusInputDemo,
  SilentCounterDemo,
  ThemeContextDemo,
} from "./lazyReactDemos";

export const reactDemoComponents = {
  GreetingDemo,
  StarRatingDemo,
  AvatarDemo,
  UserCardDemo,
  BadgeDemo,
  ListDemo,
  FilterListDemo,
  CounterDemo,
  ToggleDemo,
  ColorPickerDemo,
  LikeButtonDemo,
  KeyPressDemo,
  TextMirrorDemo,
  SignupFormDemo,
  TemperatureDemo,
  ClockDemo,
  WindowWidthDemo,
  DataFetchDemo,
  PanelDemo,
  SlotsDemo,
  TabsDemo,
  ChildrenCountDemo,
  UseToggleDemo,
  StopwatchDemo,
  UseLocalStorageDemo,
  TodoDemo,
  AuthToggleDemo,
  CartBadgeDemo,
  ImmutableListDemo,
  SettingsObjectDemo,
  FocusInputDemo,
  SilentCounterDemo,
  ThemeContextDemo,
};
