// Members of the JDK types the learn content reaches for, keyed by simple
// type name. This is what makes `s.` after `String s` list String's
// methods without a language server: the Java playground compiles at Java 8,
// so every local has an explicit declared type, and the document-symbol
// pass (documentSymbols.ts) resolves the receiver's declared type here.
// Return types use the declaring type's own placeholder letters (`E`,
// `K`, `V`, `T`); the resolver substitutes the receiver's generic arguments.

export interface JavaMember {
  name: string;
  /** Parameter list, shown as the popup detail. Empty for fields. */
  sig: string;
  /** Return (or field) type, for one-hop chains like `s.trim().`. */
  ret: string;
  /** Reachable through the type name (`Math.max`), not an instance. */
  static?: boolean;
  /** A field or constant rather than a method. */
  field?: boolean;
}

const m = (name: string, sig: string, ret: string): JavaMember => ({
  name,
  sig,
  ret,
});
const s = (name: string, sig: string, ret: string): JavaMember => ({
  name,
  sig,
  ret,
  static: true,
});
const f = (name: string, ret: string, isStatic = false): JavaMember => ({
  name,
  sig: "",
  ret,
  field: true,
  static: isStatic || undefined,
});

/** Supertypes whose members a type also offers, most specific first. */
export const JAVA_SUPERTYPES: Record<string, string[]> = {
  String: ["CharSequence", "Object"],
  StringBuilder: ["CharSequence", "Object"],
  Integer: ["Number", "Object"],
  Long: ["Number", "Object"],
  Double: ["Number", "Object"],
  Float: ["Number", "Object"],
  Short: ["Number", "Object"],
  Byte: ["Number", "Object"],
  Boolean: ["Object"],
  Character: ["Object"],
  List: ["Collection", "Iterable", "Object"],
  ArrayList: ["List", "Collection", "Iterable", "Object"],
  LinkedList: ["List", "Deque", "Collection", "Iterable", "Object"],
  Set: ["Collection", "Iterable", "Object"],
  HashSet: ["Set", "Collection", "Iterable", "Object"],
  LinkedHashSet: ["Set", "Collection", "Iterable", "Object"],
  TreeSet: ["Set", "Collection", "Iterable", "Object"],
  Map: ["Object"],
  HashMap: ["Map", "Object"],
  LinkedHashMap: ["Map", "Object"],
  TreeMap: ["Map", "Object"],
  Deque: ["Collection", "Iterable", "Object"],
  ArrayDeque: ["Deque", "Collection", "Iterable", "Object"],
  Queue: ["Collection", "Iterable", "Object"],
  Stack: ["List", "Collection", "Iterable", "Object"],
  PriorityQueue: ["Queue", "Collection", "Iterable", "Object"],
  Scanner: ["Object"],
  Random: ["Object"],
  Optional: ["Object"],
  Stream: ["Object"],
  IntStream: ["Object"],
  Exception: ["Throwable", "Object"],
  RuntimeException: ["Exception", "Throwable", "Object"],
  Thread: ["Object"],
  Iterator: ["Object"],
  Entry: ["Object"],
  PrintStream: ["Object"],
  InputStream: ["Object"],
};

/** Generic parameter names per type, in declaration order. */
export const JAVA_TYPE_PARAMS: Record<string, string[]> = {
  List: ["E"],
  ArrayList: ["E"],
  LinkedList: ["E"],
  Set: ["E"],
  HashSet: ["E"],
  LinkedHashSet: ["E"],
  TreeSet: ["E"],
  Collection: ["E"],
  Iterable: ["E"],
  Iterator: ["E"],
  Deque: ["E"],
  ArrayDeque: ["E"],
  Queue: ["E"],
  Stack: ["E"],
  PriorityQueue: ["E"],
  Map: ["K", "V"],
  HashMap: ["K", "V"],
  LinkedHashMap: ["K", "V"],
  TreeMap: ["K", "V"],
  Entry: ["K", "V"],
  Optional: ["T"],
  Stream: ["T"],
};

/** Well-known static fields whose type is not the receiver's own. */
export const JAVA_STATIC_RECEIVERS: Record<string, string> = {
  "System.out": "PrintStream",
  "System.err": "PrintStream",
  "System.in": "InputStream",
};

export const JAVA_MEMBERS: Record<string, readonly JavaMember[]> = {
  Object: [
    m("equals", "(Object obj)", "boolean"),
    m("hashCode", "()", "int"),
    m("toString", "()", "String"),
    m("getClass", "()", "Class"),
  ],
  CharSequence: [
    m("length", "()", "int"),
    m("charAt", "(int index)", "char"),
    m("subSequence", "(int start, int end)", "CharSequence"),
    m("toString", "()", "String"),
  ],
  String: [
    m("length", "()", "int"),
    m("charAt", "(int index)", "char"),
    m("substring", "(int beginIndex, int endIndex)", "String"),
    m("indexOf", "(String str)", "int"),
    m("lastIndexOf", "(String str)", "int"),
    m("contains", "(CharSequence s)", "boolean"),
    m("startsWith", "(String prefix)", "boolean"),
    m("endsWith", "(String suffix)", "boolean"),
    m("equals", "(Object other)", "boolean"),
    m("equalsIgnoreCase", "(String other)", "boolean"),
    m("compareTo", "(String other)", "int"),
    m("compareToIgnoreCase", "(String other)", "int"),
    m("toUpperCase", "()", "String"),
    m("toLowerCase", "()", "String"),
    m("trim", "()", "String"),
    m("isEmpty", "()", "boolean"),
    m("split", "(String regex)", "String[]"),
    m("replace", "(CharSequence target, CharSequence replacement)", "String"),
    m("replaceAll", "(String regex, String replacement)", "String"),
    m("replaceFirst", "(String regex, String replacement)", "String"),
    m("matches", "(String regex)", "boolean"),
    m("toCharArray", "()", "char[]"),
    m("concat", "(String str)", "String"),
    m("hashCode", "()", "int"),
    s("valueOf", "(Object obj)", "String"),
    s("format", "(String format, Object... args)", "String"),
    s("join", "(CharSequence delimiter, CharSequence... elements)", "String"),
    s("copyValueOf", "(char[] data)", "String"),
  ],
  StringBuilder: [
    m("append", "(Object obj)", "StringBuilder"),
    m("insert", "(int offset, String str)", "StringBuilder"),
    m("reverse", "()", "StringBuilder"),
    m("toString", "()", "String"),
    m("length", "()", "int"),
    m("charAt", "(int index)", "char"),
    m("setCharAt", "(int index, char ch)", "void"),
    m("deleteCharAt", "(int index)", "StringBuilder"),
    m("delete", "(int start, int end)", "StringBuilder"),
    m("replace", "(int start, int end, String str)", "StringBuilder"),
    m("indexOf", "(String str)", "int"),
    m("setLength", "(int newLength)", "void"),
    m("capacity", "()", "int"),
  ],
  Number: [
    m("intValue", "()", "int"),
    m("longValue", "()", "long"),
    m("doubleValue", "()", "double"),
    m("floatValue", "()", "float"),
  ],
  Integer: [
    s("parseInt", "(String s)", "int"),
    s("valueOf", "(String s)", "Integer"),
    s("toString", "(int i)", "String"),
    s("toBinaryString", "(int i)", "String"),
    s("toHexString", "(int i)", "String"),
    s("compare", "(int x, int y)", "int"),
    s("max", "(int a, int b)", "int"),
    s("min", "(int a, int b)", "int"),
    s("sum", "(int a, int b)", "int"),
    f("MAX_VALUE", "int", true),
    f("MIN_VALUE", "int", true),
    m("compareTo", "(Integer other)", "int"),
    m("equals", "(Object obj)", "boolean"),
  ],
  Long: [
    s("parseLong", "(String s)", "long"),
    s("valueOf", "(String s)", "Long"),
    s("toString", "(long l)", "String"),
    s("compare", "(long x, long y)", "int"),
    f("MAX_VALUE", "long", true),
    f("MIN_VALUE", "long", true),
    m("compareTo", "(Long other)", "int"),
  ],
  Double: [
    s("parseDouble", "(String s)", "double"),
    s("valueOf", "(String s)", "Double"),
    s("toString", "(double d)", "String"),
    s("isNaN", "(double v)", "boolean"),
    s("isInfinite", "(double v)", "boolean"),
    s("compare", "(double d1, double d2)", "int"),
    f("MAX_VALUE", "double", true),
    f("MIN_VALUE", "double", true),
    f("NaN", "double", true),
    f("POSITIVE_INFINITY", "double", true),
    m("compareTo", "(Double other)", "int"),
    m("isNaN", "()", "boolean"),
  ],
  Float: [
    s("parseFloat", "(String s)", "float"),
    s("valueOf", "(String s)", "Float"),
    f("MAX_VALUE", "float", true),
    f("MIN_VALUE", "float", true),
  ],
  Boolean: [
    s("parseBoolean", "(String s)", "boolean"),
    s("valueOf", "(String s)", "Boolean"),
    s("toString", "(boolean b)", "String"),
    f("TRUE", "Boolean", true),
    f("FALSE", "Boolean", true),
    m("booleanValue", "()", "boolean"),
  ],
  Character: [
    s("isDigit", "(char ch)", "boolean"),
    s("isLetter", "(char ch)", "boolean"),
    s("isLetterOrDigit", "(char ch)", "boolean"),
    s("isUpperCase", "(char ch)", "boolean"),
    s("isLowerCase", "(char ch)", "boolean"),
    s("isWhitespace", "(char ch)", "boolean"),
    s("isAlphabetic", "(int codePoint)", "boolean"),
    s("toUpperCase", "(char ch)", "char"),
    s("toLowerCase", "(char ch)", "char"),
    s("getNumericValue", "(char ch)", "int"),
    s("toString", "(char c)", "String"),
    m("charValue", "()", "char"),
  ],
  Math: [
    s("abs", "(double a)", "double"),
    s("max", "(double a, double b)", "double"),
    s("min", "(double a, double b)", "double"),
    s("pow", "(double a, double b)", "double"),
    s("sqrt", "(double a)", "double"),
    s("cbrt", "(double a)", "double"),
    s("floor", "(double a)", "double"),
    s("ceil", "(double a)", "double"),
    s("round", "(double a)", "long"),
    s("random", "()", "double"),
    s("sin", "(double a)", "double"),
    s("cos", "(double a)", "double"),
    s("tan", "(double a)", "double"),
    s("atan2", "(double y, double x)", "double"),
    s("log", "(double a)", "double"),
    s("log10", "(double a)", "double"),
    s("exp", "(double a)", "double"),
    s("hypot", "(double x, double y)", "double"),
    s("signum", "(double d)", "double"),
    s("floorDiv", "(int x, int y)", "int"),
    s("floorMod", "(int x, int y)", "int"),
    s("toRadians", "(double angdeg)", "double"),
    s("toDegrees", "(double angrad)", "double"),
    f("PI", "double", true),
    f("E", "double", true),
  ],
  System: [
    f("out", "PrintStream", true),
    f("err", "PrintStream", true),
    f("in", "InputStream", true),
    s("currentTimeMillis", "()", "long"),
    s("nanoTime", "()", "long"),
    s("exit", "(int status)", "void"),
    s("arraycopy", "(Object src, int srcPos, Object dest, int destPos, int length)", "void"),
    s("getProperty", "(String key)", "String"),
    s("getenv", "(String name)", "String"),
    s("lineSeparator", "()", "String"),
    s("identityHashCode", "(Object x)", "int"),
  ],
  PrintStream: [
    m("println", "(Object x)", "void"),
    m("print", "(Object x)", "void"),
    m("printf", "(String format, Object... args)", "PrintStream"),
    m("format", "(String format, Object... args)", "PrintStream"),
    m("flush", "()", "void"),
  ],
  InputStream: [
    m("read", "()", "int"),
    m("available", "()", "int"),
    m("close", "()", "void"),
  ],
  Iterable: [
    m("iterator", "()", "Iterator<E>"),
    m("forEach", "(Consumer<E> action)", "void"),
  ],
  Iterator: [
    m("hasNext", "()", "boolean"),
    m("next", "()", "E"),
    m("remove", "()", "void"),
  ],
  Collection: [
    m("size", "()", "int"),
    m("isEmpty", "()", "boolean"),
    m("contains", "(Object o)", "boolean"),
    m("add", "(E e)", "boolean"),
    m("remove", "(Object o)", "boolean"),
    m("addAll", "(Collection<E> c)", "boolean"),
    m("removeAll", "(Collection<?> c)", "boolean"),
    m("retainAll", "(Collection<?> c)", "boolean"),
    m("removeIf", "(Predicate<E> filter)", "boolean"),
    m("clear", "()", "void"),
    m("stream", "()", "Stream<E>"),
    m("toArray", "()", "Object[]"),
  ],
  List: [
    m("get", "(int index)", "E"),
    m("set", "(int index, E element)", "E"),
    m("add", "(int index, E element)", "void"),
    m("remove", "(int index)", "E"),
    m("indexOf", "(Object o)", "int"),
    m("lastIndexOf", "(Object o)", "int"),
    m("subList", "(int fromIndex, int toIndex)", "List<E>"),
    m("sort", "(Comparator<E> c)", "void"),
    m("listIterator", "()", "ListIterator<E>"),
  ],
  ArrayList: [
    m("ensureCapacity", "(int minCapacity)", "void"),
    m("trimToSize", "()", "void"),
  ],
  Deque: [
    m("addFirst", "(E e)", "void"),
    m("addLast", "(E e)", "void"),
    m("offerFirst", "(E e)", "boolean"),
    m("offerLast", "(E e)", "boolean"),
    m("getFirst", "()", "E"),
    m("getLast", "()", "E"),
    m("peekFirst", "()", "E"),
    m("peekLast", "()", "E"),
    m("removeFirst", "()", "E"),
    m("removeLast", "()", "E"),
    m("pollFirst", "()", "E"),
    m("pollLast", "()", "E"),
    m("push", "(E e)", "void"),
    m("pop", "()", "E"),
    m("peek", "()", "E"),
    m("poll", "()", "E"),
    m("offer", "(E e)", "boolean"),
  ],
  Queue: [
    m("offer", "(E e)", "boolean"),
    m("poll", "()", "E"),
    m("peek", "()", "E"),
    m("element", "()", "E"),
  ],
  Stack: [
    m("push", "(E item)", "E"),
    m("pop", "()", "E"),
    m("peek", "()", "E"),
    m("empty", "()", "boolean"),
    m("search", "(Object o)", "int"),
  ],
  Set: [],
  TreeSet: [
    m("first", "()", "E"),
    m("last", "()", "E"),
    m("floor", "(E e)", "E"),
    m("ceiling", "(E e)", "E"),
    m("headSet", "(E toElement)", "SortedSet<E>"),
    m("tailSet", "(E fromElement)", "SortedSet<E>"),
  ],
  Map: [
    m("get", "(Object key)", "V"),
    m("put", "(K key, V value)", "V"),
    m("containsKey", "(Object key)", "boolean"),
    m("containsValue", "(Object value)", "boolean"),
    m("remove", "(Object key)", "V"),
    m("keySet", "()", "Set<K>"),
    m("values", "()", "Collection<V>"),
    m("entrySet", "()", "Set<Entry<K,V>>"),
    m("size", "()", "int"),
    m("isEmpty", "()", "boolean"),
    m("getOrDefault", "(Object key, V defaultValue)", "V"),
    m("putIfAbsent", "(K key, V value)", "V"),
    m("putAll", "(Map<K,V> m)", "void"),
    m("forEach", "(BiConsumer<K,V> action)", "void"),
    m("merge", "(K key, V value, BiFunction<V,V,V> remapping)", "V"),
    m("computeIfAbsent", "(K key, Function<K,V> mapping)", "V"),
    m("clear", "()", "void"),
  ],
  TreeMap: [
    m("firstKey", "()", "K"),
    m("lastKey", "()", "K"),
    m("floorKey", "(K key)", "K"),
    m("ceilingKey", "(K key)", "K"),
    m("headMap", "(K toKey)", "SortedMap<K,V>"),
    m("tailMap", "(K fromKey)", "SortedMap<K,V>"),
    m("firstEntry", "()", "Entry<K,V>"),
    m("lastEntry", "()", "Entry<K,V>"),
  ],
  Entry: [
    m("getKey", "()", "K"),
    m("getValue", "()", "V"),
    m("setValue", "(V value)", "V"),
  ],
  Scanner: [
    m("nextInt", "()", "int"),
    m("nextLine", "()", "String"),
    m("next", "()", "String"),
    m("nextDouble", "()", "double"),
    m("nextLong", "()", "long"),
    m("nextBoolean", "()", "boolean"),
    m("hasNext", "()", "boolean"),
    m("hasNextInt", "()", "boolean"),
    m("hasNextLine", "()", "boolean"),
    m("hasNextDouble", "()", "boolean"),
    m("close", "()", "void"),
  ],
  Arrays: [
    s("sort", "(T[] a)", "void"),
    s("toString", "(T[] a)", "String"),
    s("deepToString", "(Object[] a)", "String"),
    s("asList", "(T... a)", "List<T>"),
    s("fill", "(T[] a, T val)", "void"),
    s("copyOf", "(T[] original, int newLength)", "T[]"),
    s("copyOfRange", "(T[] original, int from, int to)", "T[]"),
    s("equals", "(T[] a, T[] a2)", "boolean"),
    s("stream", "(T[] array)", "Stream<T>"),
    s("binarySearch", "(T[] a, T key)", "int"),
  ],
  Collections: [
    s("sort", "(List<T> list)", "void"),
    s("reverse", "(List<?> list)", "void"),
    s("shuffle", "(List<?> list)", "void"),
    s("max", "(Collection<T> coll)", "T"),
    s("min", "(Collection<T> coll)", "T"),
    s("swap", "(List<?> list, int i, int j)", "void"),
    s("frequency", "(Collection<?> c, Object o)", "int"),
    s("unmodifiableList", "(List<T> list)", "List<T>"),
    s("emptyList", "()", "List<T>"),
    s("nCopies", "(int n, T o)", "List<T>"),
    s("reverseOrder", "()", "Comparator<T>"),
  ],
  Optional: [
    m("isPresent", "()", "boolean"),
    m("get", "()", "T"),
    m("orElse", "(T other)", "T"),
    m("orElseGet", "(Supplier<T> supplier)", "T"),
    m("orElseThrow", "()", "T"),
    m("ifPresent", "(Consumer<T> action)", "void"),
    m("map", "(Function<T,U> mapper)", "Optional<U>"),
    m("filter", "(Predicate<T> predicate)", "Optional<T>"),
    s("of", "(T value)", "Optional<T>"),
    s("ofNullable", "(T value)", "Optional<T>"),
    s("empty", "()", "Optional<T>"),
  ],
  Random: [
    m("nextInt", "(int bound)", "int"),
    m("nextDouble", "()", "double"),
    m("nextBoolean", "()", "boolean"),
    m("nextLong", "()", "long"),
    m("nextGaussian", "()", "double"),
    m("setSeed", "(long seed)", "void"),
  ],
  Stream: [
    m("filter", "(Predicate<T> predicate)", "Stream<T>"),
    m("map", "(Function<T,R> mapper)", "Stream<R>"),
    m("forEach", "(Consumer<T> action)", "void"),
    m("collect", "(Collector<T,A,R> collector)", "R"),
    m("count", "()", "long"),
    m("sorted", "()", "Stream<T>"),
    m("distinct", "()", "Stream<T>"),
    m("limit", "(long maxSize)", "Stream<T>"),
    m("skip", "(long n)", "Stream<T>"),
    m("reduce", "(T identity, BinaryOperator<T> accumulator)", "T"),
    m("mapToInt", "(ToIntFunction<T> mapper)", "IntStream"),
    m("mapToDouble", "(ToDoubleFunction<T> mapper)", "DoubleStream"),
    m("anyMatch", "(Predicate<T> predicate)", "boolean"),
    m("allMatch", "(Predicate<T> predicate)", "boolean"),
    m("noneMatch", "(Predicate<T> predicate)", "boolean"),
    m("findFirst", "()", "Optional<T>"),
    m("min", "(Comparator<T> comparator)", "Optional<T>"),
    m("max", "(Comparator<T> comparator)", "Optional<T>"),
    m("toArray", "()", "Object[]"),
  ],
  IntStream: [
    m("sum", "()", "int"),
    m("average", "()", "OptionalDouble"),
    m("max", "()", "OptionalInt"),
    m("min", "()", "OptionalInt"),
    m("count", "()", "long"),
    m("map", "(IntUnaryOperator mapper)", "IntStream"),
    m("filter", "(IntPredicate predicate)", "IntStream"),
    m("forEach", "(IntConsumer action)", "void"),
    m("boxed", "()", "Stream<Integer>"),
    m("toArray", "()", "int[]"),
    s("range", "(int startInclusive, int endExclusive)", "IntStream"),
    s("rangeClosed", "(int startInclusive, int endInclusive)", "IntStream"),
    s("of", "(int... values)", "IntStream"),
  ],
  Throwable: [
    m("getMessage", "()", "String"),
    m("printStackTrace", "()", "void"),
    m("getCause", "()", "Throwable"),
    m("getStackTrace", "()", "StackTraceElement[]"),
  ],
  Exception: [],
  RuntimeException: [],
  Thread: [
    s("sleep", "(long millis)", "void"),
    s("currentThread", "()", "Thread"),
    m("start", "()", "void"),
    m("join", "()", "void"),
    m("interrupt", "()", "void"),
    m("getName", "()", "String"),
    m("isAlive", "()", "boolean"),
  ],
};

/** Members every array has. */
export const JAVA_ARRAY_MEMBERS: readonly JavaMember[] = [
  f("length", "int"),
  m("clone", "()", "T[]"),
];
