import type { Completion } from "@codemirror/autocomplete";

// Pre-boot completion fallback for the R playground surfaces. Once WebR
// is running, `LanguageRuntime.complete()` answers from R's own
// completion engine (utils:::.completeToken) and this list is suppressed
// — see `languageCompletion.ts`. Curated for the base-R vocabulary the
// learn content leans on.

const kw = (label: string): Completion => ({ label, type: "keyword" });
const fn = (label: string, detail: string): Completion => ({
  label,
  type: "function",
  detail,
});
const cn = (label: string): Completion => ({ label, type: "constant" });

export const R_COMPLETIONS: readonly Completion[] = [
  // Language keywords & constants
  ...["if", "else", "for", "while", "repeat", "function", "break", "next",
    "in", "return"].map(kw),
  ...["TRUE", "FALSE", "NULL", "NA", "NA_integer_", "NA_real_",
    "NA_character_", "Inf", "NaN"].map(cn),

  // Vectors & sequences
  fn("c", "(...)"),
  fn("vector", "(mode, length)"),
  fn("seq", "(from, to, by)"),
  fn("seq_len", "(length.out)"),
  fn("seq_along", "(along.with)"),
  fn("rep", "(x, times)"),
  fn("length", "(x)"),
  fn("rev", "(x)"),
  fn("sort", "(x, decreasing = FALSE)"),
  fn("order", "(...)"),
  fn("unique", "(x)"),
  fn("which", "(x)"),
  fn("which.max", "(x)"),
  fn("which.min", "(x)"),
  fn("range", "(x)"),

  // Math & statistics
  fn("sum", "(..., na.rm = FALSE)"),
  fn("mean", "(x, na.rm = FALSE)"),
  fn("median", "(x, na.rm = FALSE)"),
  fn("min", "(..., na.rm = FALSE)"),
  fn("max", "(..., na.rm = FALSE)"),
  fn("sd", "(x, na.rm = FALSE)"),
  fn("var", "(x, na.rm = FALSE)"),
  fn("quantile", "(x, probs)"),
  fn("cor", "(x, y)"),
  fn("round", "(x, digits = 0)"),
  fn("floor", "(x)"),
  fn("ceiling", "(x)"),
  fn("abs", "(x)"),
  fn("sqrt", "(x)"),
  fn("exp", "(x)"),
  fn("log", "(x, base = exp(1))"),
  fn("log2", "(x)"),
  fn("log10", "(x)"),
  fn("cumsum", "(x)"),
  fn("prod", "(...)"),
  fn("table", "(...)"),
  fn("sample", "(x, size, replace = FALSE)"),
  fn("runif", "(n, min = 0, max = 1)"),
  fn("rnorm", "(n, mean = 0, sd = 1)"),
  fn("set.seed", "(seed)"),

  // Data frames & structures
  fn("data.frame", "(...)"),
  fn("head", "(x, n = 6)"),
  fn("tail", "(x, n = 6)"),
  fn("nrow", "(x)"),
  fn("ncol", "(x)"),
  fn("dim", "(x)"),
  fn("names", "(x)"),
  fn("colnames", "(x)"),
  fn("rownames", "(x)"),
  fn("str", "(object)"),
  fn("summary", "(object)"),
  fn("subset", "(x, subset, select)"),
  fn("merge", "(x, y, by)"),
  fn("rbind", "(...)"),
  fn("cbind", "(...)"),
  fn("aggregate", "(formula, data, FUN)"),
  fn("list", "(...)"),
  fn("unlist", "(x)"),
  fn("matrix", "(data, nrow, ncol)"),
  fn("factor", "(x, levels)"),
  fn("levels", "(x)"),
  fn("t", "(x)"),

  // Apply family
  fn("apply", "(X, MARGIN, FUN)"),
  fn("lapply", "(X, FUN)"),
  fn("sapply", "(X, FUN)"),
  fn("vapply", "(X, FUN, FUN.VALUE)"),
  fn("mapply", "(FUN, ...)"),
  fn("tapply", "(X, INDEX, FUN)"),
  fn("do.call", "(what, args)"),
  fn("Reduce", "(f, x)"),
  fn("Filter", "(f, x)"),
  fn("Map", "(f, ...)"),

  // Strings
  fn("paste", "(..., sep = \" \")"),
  fn("paste0", "(...)"),
  fn("sprintf", "(fmt, ...)"),
  fn("format", "(x, ...)"),
  fn("nchar", "(x)"),
  fn("substr", "(x, start, stop)"),
  fn("strsplit", "(x, split)"),
  fn("gsub", "(pattern, replacement, x)"),
  fn("sub", "(pattern, replacement, x)"),
  fn("grepl", "(pattern, x)"),
  fn("grep", "(pattern, x)"),
  fn("toupper", "(x)"),
  fn("tolower", "(x)"),
  fn("trimws", "(x)"),

  // Types & predicates
  fn("is.na", "(x)"),
  fn("is.null", "(x)"),
  fn("is.numeric", "(x)"),
  fn("is.character", "(x)"),
  fn("is.function", "(x)"),
  fn("as.numeric", "(x)"),
  fn("as.integer", "(x)"),
  fn("as.character", "(x)"),
  fn("as.logical", "(x)"),
  fn("as.factor", "(x)"),
  fn("as.Date", "(x, format)"),
  fn("class", "(x)"),
  fn("typeof", "(x)"),
  fn("inherits", "(x, what)"),
  fn("identical", "(x, y)"),
  fn("all", "(..., na.rm = FALSE)"),
  fn("any", "(..., na.rm = FALSE)"),
  fn("ifelse", "(test, yes, no)"),
  fn("stopifnot", "(...)"),
  fn("tryCatch", "(expr, error)"),

  // I/O & session
  fn("print", "(x)"),
  fn("cat", "(..., sep = \" \")"),
  fn("message", "(...)"),
  fn("warning", "(...)"),
  fn("stop", "(...)"),
  fn("library", "(package)"),
  fn("require", "(package)"),
  fn("install.packages", "(pkgs)"),
  fn("read.csv", "(file, header = TRUE)"),
  fn("write.csv", "(x, file)"),
  fn("readLines", "(con)"),
  fn("writeLines", "(text, con)"),
  fn("download.file", "(url, destfile)"),
  fn("Sys.time", "()"),
  fn("Sys.Date", "()"),
  fn("getwd", "()"),
  fn("ls", "()"),
  fn("rm", "(...)"),
  fn("help", "(topic)"),

  // Plotting (base graphics)
  fn("plot", "(x, y, type, main, xlab, ylab)"),
  fn("lines", "(x, y)"),
  fn("points", "(x, y)"),
  fn("hist", "(x, breaks)"),
  fn("barplot", "(height)"),
  fn("boxplot", "(x)"),
  fn("abline", "(a, b, h, v)"),
  fn("legend", "(x, legend)"),
  fn("text", "(x, y, labels)"),
  fn("par", "(...)"),
];
