/**
 * Canonical site origin + default social-share image, shared by layout
 * metadata, the sitemap, and robots.txt so they never drift. Keep
 * NEXT_PUBLIC_SITE_URL pointed at production even on previews: canonical tags
 * must point at the canonical location or search engines may index the
 * preview.
 */
export const SITE_URL =
  process.env.NEXT_PUBLIC_SITE_URL ?? "https://dataslope.com";

/**
 * Default OpenGraph / Twitter share image (generated by
 * scripts/build-og-image.mjs). Relative on purpose: it resolves against
 * `metadataBase`.
 */
export const OG_IMAGE = {
  url: "/og-default.png",
  width: 1200,
  height: 630,
  alt: "DataSlope, learn by running code in your browser",
} as const;
