/**
 * Fumadocs source loader.
 *
 * Wraps the MDX content collection defined in `source.config.ts` (and
 * generated by `fumadocs-mdx` into `.source/`) and exposes it through
 * Fumadocs's `loader()` helper, scoped to the `/learn` URL prefix so
 * the docs site coexists with the existing `/playground` routes.
 */
import { loader } from "fumadocs-core/source";
import { docs } from "@/.source/server";

export const source = loader({
  baseUrl: "/learn",
  source: docs.toFumadocsSource(),
});
