/**
 * Fumadocs source loaders.
 *
 * Wrap the MDX content collections defined in `source.config.ts` (and
 * generated by `fumadocs-mdx` into `.source/`) and expose them through
 * Fumadocs's `loader()` helper:
 *  - `courseSource`    → `/courses`      (the courses)
 *  - `devSource`       → `/fumadocs-dev` (dev-only component gallery)
 *  - `interviewSource` → `/interview-prep` (interview prep, by role)
 *
 * All coexist with the plain-CSS `/playground` routes.
 */
import { loader } from "fumadocs-core/source";
import type { Node, Root } from "fumadocs-core/page-tree";
// `dynamic` mode (see `source.config.ts`) emits each collection from
// `.source/dynamic`, where a page body is compiled on demand from disk at
// request time instead of being bundled into the route graph.
import { courses, fumadocsDev, interview } from "@/.source/dynamic";

// No `lucideIconsPlugin()`: it resolves page-tree icon names through
// lucide-react's `icons` map, which imports every icon (~1 MB, ~260 KB gzipped
// across its two copies in the Worker) for a feature no page uses. Without it
// an `icon` in frontmatter or meta.json reaches the sidebar as a bare string,
// so if content ever names one, map the few it needs explicitly here rather
// than bringing the plugin back.
export const courseSource = loader({
  baseUrl: "/courses",
  source: courses.toFumadocsSource(),
});

export const devSource = loader({
  baseUrl: "/fumadocs-dev",
  source: fumadocsDev.toFumadocsSource(),
});

export const interviewSource = loader({
  baseUrl: "/interview-prep",
  source: interview.toFumadocsSource(),
});

/**
 * A section's page tree cut down to the one top-level folder (a course, or an
 * interview-prep role) holding the pages under `prefix`, e.g.
 * `/courses/python-basics`. `<DocsLayout>` is a client component, so the tree
 * it is handed is serialized into every page's HTML, and the whole course
 * tree is ~370 KB (every lesson of every course, descriptions included) where
 * the sidebar only ever draws one course: each course folder is a Fumadocs
 * root. Nothing else reads the rest. The layout re-renders on every lesson
 * anyway, since its segment is the whole catch-all.
 *
 * The root gets its own `$id` because Fumadocs memoizes the tree on it. A
 * prefix that matches no folder keeps the full tree.
 */
export function scopedPageTree(tree: Root, prefix: string): Root {
  const owns = (node: Node): boolean =>
    node.type === "page"
      ? node.url === prefix || node.url.startsWith(`${prefix}/`)
      : node.type === "folder" &&
        ((node.index ? owns(node.index) : false) || node.children.some(owns));
  const folder = tree.children.find(
    (node) => node.type === "folder" && owns(node),
  );
  if (!folder) return tree;
  return { ...tree, $id: `${tree.$id ?? "root"}:${prefix}`, children: [folder] };
}
