<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RuntimeIdentifier>browser-wasm</RuntimeIdentifier>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Nullable>enable</Nullable>
    <InvariantGlobalization>true</InvariantGlobalization>
    <WasmMainJSPath>main.mjs</WasmMainJSPath>
    <PublishTrimmed>false</PublishTrimmed>
    <WasmBuildNative>true</WasmBuildNative>
    <WasmGenerateAppBundle>true</WasmGenerateAppBundle>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Scripting" Version="4.14.0" />
  </ItemGroup>
</Project>
