/**
 * The chart review queue: which generated figures an admin wants redrawn, and
 * the note saying what is wrong with each one.
 *
 * Storage is D1 database **`dataslope-illustrations`**, table
 * **`chart_regen_marks`**, reached through the `ILLUSTRATIONS_DB` binding
 * (schema in `migrations/illustrations/0003_…`). That database holds authoring
 * and review state rather than illustration state specifically, which is why a
 * second queue lives there instead of getting a binding of its own.
 *
 * Marks are written from `/dashboard/admin/charts` (admin-only) via
 * `/api/admin/charts`, and read back by whoever rewrites the spec. The two
 * halves of the round trip differ from the illustration queue in where the
 * middle step happens: an illustration is regenerated by a model, a chart is
 * regenerated by editing `charts/<slug>.mjs` and running
 * `npm run build:charts`. Whoever does that stamps `regenerated_at` (the SQL
 * is in the migration), and the gallery then shows the chart as waiting to be
 * looked at until an admin approves it.
 *
 * `prompt_id` is the chart slug: the file stem in `charts/<slug>.mjs`, the key
 * in `lib/generated/charts.js`, and the `slug` prop on `<Chart />`, so one
 * mark points at a spec, a rendered SVG, and every lesson using it at once.
 *
 * The mechanics live in `lib/review/marks.ts`, shared with the illustration
 * queue. This module is the chart binding of it: the table and nothing else.
 *
 * The note is optional and has no default. A chart has no single failure mode
 * anyway — a label collides, a caption asserts a number the data does not
 * support, a colour dies in dark mode, a mark silently fails to render — so
 * there was never one sentence worth substituting for a blank. Marking with
 * nothing typed means flagged, no reason given.
 */
import type { D1Database } from "@cloudflare/workers-types";
import {
  approveRegenMark as approveMark,
  listRegenMarks as listMarks,
  readMark as readOneMark,
  requestDeletion as requestDelete,
  upsertRegenMark as upsertMark,
} from "@/lib/review/marks";

export { MAX_NOTE_LENGTH, isAwaitingApproval, normalizeNote } from "@/lib/review/marks";
export type { RegenMark } from "@/lib/review/marks";

const QUEUE = "charts" as const;

/** Every row in the queue, marked ones first and oldest mark first within
 *  each group. */
export function listRegenMarks(db: D1Database) {
  return listMarks(db, QUEUE);
}

/** One row by slug, or null when the chart has never been marked. */
export function readMark(db: D1Database, promptId: string) {
  return readOneMark(db, QUEUE, promptId);
}

/** Set (or clear) the mark on one chart, keeping the note either way. */
export function upsertRegenMark(
  db: D1Database,
  input: { promptId: string; marked: boolean; note: string; markedBy?: string | null },
) {
  return upsertMark(db, QUEUE, input);
}

/** Sign off a redraw, so the chart stops showing as waiting for a look. */
export function approveRegenMark(
  db: D1Database,
  input: { promptId: string; approvedBy?: string | null },
) {
  return approveMark(db, QUEUE, input);
}

/** Ask for this chart to be deleted from the repository, or withdraw the ask.
 *  The gallery records the decision; the deletion itself is a commit, made by
 *  whoever reads the queue back (see migrations/illustrations/0004_…). */
export function requestDeletion(
  db: D1Database,
  input: { promptId: string; requested: boolean; reason: string; requestedBy?: string | null },
) {
  return requestDelete(db, QUEUE, input);
}
