#!/usr/bin/env node
/**
 * Optimize the raster content images and generate their manifest (slug →
 * {hash, width, height, formats} in lib/generated/images.js), which is how
 * `<Image>` reserves layout space without shipping the raw file. Encoding is
 * expensive, so unlike the cheap text generators this is incremental and its
 * outputs are committed: a source re-encodes only when its content hash
 * changes, and an unchanged tree is a true no-op with no git churn.
 *
 * Two classes of image reach `public/images/`: pre-served WebP written by
 * `scripts/promote-illustrations.mjs`, which are NOT re-encoded (a second
 * lossy pass cost ~1.8 dB PSNR to save ~3 kB) and only contribute dimensions;
 * and raster sources under `assets/images/`, encoded to `.webp` plus a
 * fallback (currently none exist; the path stays supported and tested).
 *
 * Bump `ENCODER_VERSION` after an encoder-settings change to force a one-time
 * full re-encode. With no sources it writes an empty manifest so
 * typecheck/lint/build stay green.
 */
import { createHash } from "node:crypto";
import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { dirname, extname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { readManifest, writeManifest } from "./lib/build-cache.mjs";

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const SRC_DIR = join(ROOT, "assets", "images");
const OUT_DIR = join(ROOT, "public", "images");
const MANIFEST_FILE = join(ROOT, "lib", "generated", "images.js");

// Raster source formats sharp can decode. SVG is handled inline in MDX. GIF
// is excluded: sharp reads only the first frame, silently flattening
// animations — convert to PNG/WebP first.
const SOURCE_EXTS = new Set([
  ".png",
  ".jpg",
  ".jpeg",
  ".webp",
  ".avif",
  ".tif",
  ".tiff",
]);

// Every format the encoder can emit; the prune step only touches these.
const OUTPUT_EXTS = new Set([".webp", ".png", ".jpg"]);

// Cap the longest edge: crisp at ~640px display on 2x without shipping a
// 2048px original. `withoutEnlargement` keeps smaller sources untouched.
const MAX_EDGE = 1600;

// Bump after changing the encode settings below to force a full re-encode.
const ENCODER_VERSION = "2";

/** Lowercase, strip diacritics, and hyphenate to a URL/file-safe slug.
 *  Exported for the vitest suite (__tests__/figureSlugs.test.ts). */
export function slugify(value) {
  return value
    .normalize("NFKD")
    // Combining-diacritics block, as escapes so a formatter can't mangle it.
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

/** Read the raster sources, if any. A missing folder is not an error, it just
 *  means no images have been dropped in yet. */
function listSources() {
  let entries;
  try {
    entries = readdirSync(SRC_DIR);
  } catch {
    return [];
  }
  return entries
    .filter((name) => SOURCE_EXTS.has(extname(name).toLowerCase()))
    .filter((name) => statSync(join(SRC_DIR, name)).isFile())
    .sort();
}

/** Load the prior manifest so unchanged images can be skipped. The JSON
 *  literal is pulled from the text rather than `import()`ed (which warns
 *  under the CommonJS-typed package.json); absent/unparseable → all new. */
function loadPriorManifest() {
  if (!existsSync(MANIFEST_FILE)) return {};
  try {
    const text = readFileSync(MANIFEST_FILE, "utf8");
    const match = text.match(/export default\s*(\{[\s\S]*\})\s*;?\s*$/);
    return match ? JSON.parse(match[1]) : {};
  } catch {
    return {};
  }
}

/** Serialize the manifest to its committed ES-module form. */
function renderManifest(manifest) {
  const sorted = Object.fromEntries(
    Object.keys(manifest)
      .sort()
      .map((k) => [k, manifest[k]]),
  );
  const banner =
    "// GENERATED by scripts/build-images.mjs, do not edit by hand.\n" +
    "// Committed; rebuilt (incrementally) from assets/images/*.\n";
  return `${banner}export default ${JSON.stringify(sorted, null, 2)};\n`;
}

async function main() {
  const sources = listSources();
  const prior = loadPriorManifest();

  mkdirSync(OUT_DIR, { recursive: true });
  mkdirSync(dirname(MANIFEST_FILE), { recursive: true });

  // Lazy: the "nothing changed" / "no images yet" paths never load sharp.
  let sharp = null;
  const ensureSharp = async () => {
    if (sharp) return sharp;
    try {
      ({ default: sharp } = await import("sharp"));
    } catch (err) {
      throw new Error(
        `build-images: an image needs (re)encoding but the "sharp" package ` +
          `failed to load, run \`npm install\`. (${err.message})`,
      );
    }
    return sharp;
  };

  // Sidecar for the adopt loop: file → size/mtime its hash was computed from.
  // Lives in node_modules/.cache because mtimes are per-clone and would put a
  // machine-specific diff in git.
  const statCache = readManifest(ROOT, "images-stat") ?? {};
  const nextStatCache = {};

  const manifest = {};
  const seen = new Map();
  let encoded = 0;
  let cached = 0;

  for (const name of sources) {
    const slug = slugify(name.replace(/\.[^.]+$/, ""));
    if (!slug) {
      console.warn(`build-images: skipping "${name}", empty slug.`);
      continue;
    }
    if (seen.has(slug)) {
      throw new Error(
        `build-images: "${name}" and "${seen.get(slug)}" both slugify to ` +
          `"${slug}". Rename one so every image has a unique slug.`,
      );
    }
    seen.set(slug, name);

    const input = readFileSync(join(SRC_DIR, name));
    const hash = createHash("sha256")
      .update(ENCODER_VERSION)
      .update(input)
      .digest("hex");

    // Reuse when the source is unchanged and its outputs are still on disk.
    const priorEntry = prior[slug];
    if (
      priorEntry?.hash === hash &&
      Array.isArray(priorEntry.formats) &&
      priorEntry.formats.every((ext) =>
        existsSync(join(OUT_DIR, `${slug}.${ext}`)),
      )
    ) {
      manifest[slug] = priorEntry;
      cached += 1;
      continue;
    }

    const s = await ensureSharp();
    const meta = await s(input).metadata();
    // `rotate()` honors EXIF orientation; sharp's default limitInputPixels
    // already guards decompression bombs.
    const base = s(input).rotate().resize({
      width: MAX_EDGE,
      height: MAX_EDGE,
      fit: "inside",
      withoutEnlargement: true,
    });

    const webpBuf = await base
      .clone()
      .webp({ quality: 80, alphaQuality: 100, effort: 6 })
      .toBuffer();

    // Fallback for browsers without WebP: PNG preserves transparency; JPEG is
    // far smaller for opaque images (photos, screenshots).
    let fallbackExt;
    let fallbackBuf;
    let info;
    if (meta.hasAlpha) {
      const out = await base
        .clone()
        .png({ compressionLevel: 9, effort: 10 })
        .toBuffer({ resolveWithObject: true });
      fallbackExt = "png";
      fallbackBuf = out.data;
      info = out.info;
    } else {
      const out = await base
        .clone()
        .jpeg({ quality: 82, mozjpeg: true })
        .toBuffer({ resolveWithObject: true });
      fallbackExt = "jpg";
      fallbackBuf = out.data;
      info = out.info;
    }

    writeFileSync(join(OUT_DIR, `${slug}.webp`), webpBuf);
    writeFileSync(join(OUT_DIR, `${slug}.${fallbackExt}`), fallbackBuf);
    manifest[slug] = {
      hash,
      width: info.width,
      height: info.height,
      formats: ["webp", fallbackExt],
    };
    encoded += 1;

    const webpKb = (webpBuf.length / 1024).toFixed(0);
    const fbKb = (fallbackBuf.length / 1024).toFixed(0);
    console.log(
      `build-images: encoded ${slug}  ${info.width}x${info.height}  ` +
        `webp ${webpKb}kB / ${fallbackExt} ${fbKb}kB`,
    );
  }

  // Adopt pre-served WebP (promotion wrote them; no source under
  // assets/images): record dimensions only, no re-encode. Registering them is
  // also what keeps the prune step below from deleting them.
  let adopted = 0;
  for (const file of readdirSync(OUT_DIR)) {
    if (extname(file).toLowerCase() !== ".webp") continue;
    const slug = file.replace(/\.webp$/i, "");
    if (manifest[slug]) continue; // owned by a legacy source
    const priorEntry = prior[slug];

    // Fast path: proving "unchanged" by hashing meant reading ~340 MB of
    // images on every dev/build. The sidecar records the size+mtime each hash
    // was computed from, so an untouched file is settled by `stat` alone;
    // content still decides when the stat moved.
    const st = statSync(join(OUT_DIR, file));
    const seen = statCache[file];
    if (
      seen &&
      seen.size === st.size &&
      seen.mtime === Math.round(st.mtimeMs) &&
      priorEntry?.hash === seen.hash &&
      priorEntry.formats?.length === 1
    ) {
      manifest[slug] = priorEntry;
      nextStatCache[file] = seen;
      cached += 1;
      continue;
    }

    const buf = readFileSync(join(OUT_DIR, file));
    const hash = createHash("sha256").update(ENCODER_VERSION).update(buf).digest("hex");
    nextStatCache[file] = { size: st.size, mtime: Math.round(st.mtimeMs), hash };
    if (priorEntry?.hash === hash && priorEntry.formats?.length === 1) {
      manifest[slug] = priorEntry;
      cached += 1;
      continue;
    }
    const s2 = await ensureSharp();
    const meta = await s2(buf).metadata();
    manifest[slug] = {
      hash,
      width: meta.width,
      height: meta.height,
      formats: ["webp"],
    };
    adopted += 1;
  }

  // Prune any optimized file that isn't an expected output of a current slug
  // (source removed, renamed, or its fallback format changed).
  const expected = new Set();
  for (const [slug, entry] of Object.entries(manifest)) {
    for (const ext of entry.formats) expected.add(`${slug}.${ext}`);
  }
  let pruned = 0;
  for (const file of readdirSync(OUT_DIR)) {
    if (!OUTPUT_EXTS.has(extname(file).toLowerCase())) continue;
    if (!expected.has(file)) {
      rmSync(join(OUT_DIR, file));
      pruned += 1;
    }
  }

  // Rewrite the manifest only when it actually changed, keeps the script a
  // true no-op (and produces no git diff) when nothing was re-encoded.
  const next = renderManifest(manifest);
  const current = existsSync(MANIFEST_FILE)
    ? readFileSync(MANIFEST_FILE, "utf8")
    : null;
  if (next !== current) writeFileSync(MANIFEST_FILE, next);

  // Request-time consumers get this as a static asset via lib/serverAssets.ts
  // (filesystem in dev, ASSETS binding in the Worker), keeping the manifest
  // module and created-at.js out of the API route's own bundler graph. Same
  // write-if-changed discipline; gitignored. created-at.js is generated
  // earlier in every build chain and only goes missing on a bare direct run,
  // which degrades to empty timestamps rather than failing.
  const createdAtFile = join(ROOT, "lib", "generated", "created-at.js");
  let illustrationsCreatedAt = {};
  if (existsSync(createdAtFile)) {
    const mod = await import(pathToFileURL(createdAtFile).href);
    illustrationsCreatedAt = mod.default?.illustrations ?? {};
  } else {
    console.warn(
      "build-images: lib/generated/created-at.js missing; " +
        "illustration-gallery.json gets empty timestamps",
    );
  }
  const galleryFile = join(ROOT, "public", "_gen", "illustration-gallery.json");
  const galleryJson = JSON.stringify({ images: manifest, illustrationsCreatedAt });
  mkdirSync(dirname(galleryFile), { recursive: true });
  const galleryCurrent = existsSync(galleryFile)
    ? readFileSync(galleryFile, "utf8")
    : null;
  if (galleryJson !== galleryCurrent) writeFileSync(galleryFile, galleryJson);

  // Rebuilt from scratch each run, so a pruned or renamed file drops out
  // instead of accumulating forever.
  writeManifest(ROOT, "images-stat", nextStatCache);

  console.log(
    `build-images: ${encoded} encoded, ${adopted} adopted, ${cached} cached, ` +
      `${pruned} pruned (${Object.keys(manifest).length} image(s) total)`,
  );

  // An opaque original beside its own cut-out is git weight nothing renders
  // (one earlier promotion left 1,351 of them, 151 MB). A warning, not a
  // failure: art genuinely shown with its background is legitimate, just
  // deliberate.
  const redundant = Object.keys(manifest).filter(
    (slug) => !slug.endsWith("-cutout") && manifest[`${slug}-cutout`],
  );
  if (redundant.length > 0) {
    console.warn(
      `build-images: ${redundant.length} image(s) have a cut-out beside them and ` +
        `are unlikely to be rendered; promote with --cutout-only (the default) ` +
        `or delete them, e.g. ${redundant.slice(0, 3).join(", ")}`,
    );
  }
}

// Run only when executed directly (`node scripts/build-images.mjs`), so the
// vitest suite can import the exported helpers without triggering a build.
if (
  process.argv[1] &&
  import.meta.url === pathToFileURL(process.argv[1]).href
) {
  main().catch((err) => {
    console.error(err);
    process.exit(1);
  });
}
